version: '3.8'
services:
  test_db:
    image: postgres:13
    container_name: postgres_local_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local_test_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_local_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d local_test_db"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_local_test_data:
    driver: local
