version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgres_with_seed
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local_seed_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d local_seed_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: run/Dockerfile.seed
    container_name: your_app_with_seed
    environment:
      - NODE_ENV=development
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=local_seed_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  postgres_data:
    driver: local