version: '3.8'
services:
  db:
    image: postgres:13
    container_name: test_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d local_test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    build: 
      context: ..
      dockerfile: run/Dockerfile.test
    container_name: api_test
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/test_db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data_test:
    driver: local