version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgres_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d local_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_local_data:
    driver: local 